spring.application.name=urban-nav

# Caminho para o ficheiro OSM
osm.file.path=src/main/resources/data/maputo.osm

# Porta do servidor
server.port=8080

# Aumentar timeout para carregamento do grafo (ficheiro grande)
spring.mvc.async.request-timeout=120000

# Log nivel
logging.level.com.urbanav=INFO
